version: '3'

includes:
  claude:
    taskfile: .claude
    optional: true
    flatten: true

vars:
  PROJECT: ffmpeg-sandbox
  DATA_DIR: ./.data
  INPUT_DIR: ./.data/input
  OUTPUT_DIR: ./.data/output
  LOGS_DIR: ./.data/logs
  GIT_HASH:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "dev"
  GIT_DATE:
    sh: git log -1 --format=%cd --date=format:%Y.%m.%d 2>/dev/null || echo ""

tasks:
  # ============================================
  # Default Task
  # ============================================

  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ============================================
  # Claude Tasks
  # ============================================

  claude:
    cmds:
      - claude --chrome --ide --model opus


  # ============================================
  # Docker Tasks
  # ============================================

  build:
    desc: Build the Docker image
    cmds:
      - GIT_HASH={{.GIT_HASH}} GIT_DATE={{.GIT_DATE}} docker compose build

  up:
    desc: Start the application in detached mode
    cmds:
      - docker compose up -d

  down:
    desc: Stop and remove containers
    cmds:
      - docker compose down

  restart:
    desc: Restart the application
    cmds:
      - docker compose restart

  logs:
    desc: Follow container logs
    cmds:
      - docker compose logs -f

  shell:
    desc: Open a shell in the running container
    cmds:
      - docker compose exec ffmpeg-sandbox /bin/bash

  rebuild:
    desc: Rebuild and restart the application
    deps:
      - clean:all
    cmds:
      - docker compose down
      - GIT_HASH={{.GIT_HASH}} GIT_DATE={{.GIT_DATE}} docker compose build
      - docker compose up -d

  reset:
    desc: clean and restart the application
    deps:
      - clean:all
    cmds:
      - docker compose down
      - docker compose up -d

  # ============================================
  # Local Development (without Docker)
  # ============================================

  dev:
    desc: Run locally with hot reload (requires uv)
    cmds:
      - uv run python -m app.main
    deps: [ensure-dirs]

  sync:
    desc: Install/sync dependencies with uv
    cmds:
      - uv sync

  # ============================================
  # Testing Tasks
  # ============================================

  test:
    desc: Run pytest test suite
    silent: true
    cmds:
      - uv run pytest tests/ -v

  test:cov:
    desc: Run tests with coverage report
    silent: true
    cmds:
      - uv run pytest tests/ --cov=app --cov-report=term-missing

  # ============================================
  # Cleanup Tasks (Windows-compatible via PowerShell)
  # ============================================

  clean:output:
    desc: Remove all processed audio files
    cmds:
      - pwsh -Command "Remove-Item -Path '{{.OUTPUT_DIR}}/*.mp3','{{.OUTPUT_DIR}}/*.mp4','{{.OUTPUT_DIR}}/*.webm','{{.OUTPUT_DIR}}/*.mkv' -Force -ErrorAction SilentlyContinue; Write-Host 'Cleaned output directory'"

  clean:logs:
    desc: Remove all log files
    cmds:
      - pwsh -Command "Remove-Item -Path '{{.LOGS_DIR}}/*.log' -Force -ErrorAction SilentlyContinue; Write-Host 'Cleaned logs directory'"

  clean:history:
    desc: Remove processing history
    cmds:
      - pwsh -Command "Remove-Item -Path '{{.DATA_DIR}}/history.json' -Force -ErrorAction SilentlyContinue; Write-Host 'Cleared processing history'"

  clean:metadata:
    desc: Remove per-file metadata configs
    cmds:
      - pwsh -Command "Remove-Item -Path '{{.INPUT_DIR}}/*.yml' -Force -ErrorAction SilentlyContinue; Write-Host 'Cleaned per-file metadata'"

  clean:all:
    desc: Remove all generated files (output, logs, history, metadata)
    cmds:
      - task: clean:downloads
      - task: clean:output
      - task: clean:logs
      - task: clean:history
      - task: clean:metadata

  clean:docker:
    desc: Remove Docker containers, images, and volumes
    cmds:
      - docker compose down -v --rmi local
      - pwsh -Command "Write-Host 'Cleaned Docker resources'"

  clean:venv:
    desc: Remove Python virtual environment
    cmds:
      - pwsh -Command "Remove-Item -Path '.venv' -Recurse -Force -ErrorAction SilentlyContinue; Write-Host 'Removed .venv directory'"

  clean:pycache:
    desc: Remove Python cache files
    cmds:
      - pwsh -Command "Get-ChildItem -Path . -Recurse -Directory -Filter '__pycache__' -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue; Get-ChildItem -Path . -Recurse -Filter '*.pyc' -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue; Write-Host 'Cleaned Python cache'"

  nuke:
    desc: Full cleanup (all generated files + Docker + venv)
    cmds:
      - task: clean:all
      - task: clean:docker
      - task: clean:venv
      - task: clean:pycache

  # ============================================
  # Download Tasks
  # ============================================

  clean:downloads:
    desc: Remove all downloaded video files from input
    cmds:
      - pwsh -Command "Remove-Item -Path '{{.INPUT_DIR}}/*.mp4','{{.INPUT_DIR}}/*.mkv','{{.INPUT_DIR}}/*.webm' -Force -ErrorAction SilentlyContinue; Write-Host 'Cleaned downloaded videos'"

  download:test:
    desc: Test yt-dlp installation
    cmds:
      - pwsh ./scripts/test-ytdlp.ps1

  # ============================================
  # Utility Tasks (Windows-compatible)
  # ============================================

  ensure-dirs:
    desc: Create required directories
    cmds:
      - pwsh -Command "New-Item -ItemType Directory -Path '{{.INPUT_DIR}}','{{.OUTPUT_DIR}}','{{.LOGS_DIR}}' -Force -ErrorAction SilentlyContinue | Out-Null"
    silent: true

  list:input:
    desc: List files in input directory
    cmds:
      - pwsh -Command "Get-ChildItem -Path '{{.INPUT_DIR}}' | Format-Table Name,Length,LastWriteTime -AutoSize"

  list:output:
    desc: List processed files in output directory
    cmds:
      - pwsh -Command "Get-ChildItem -Path '{{.OUTPUT_DIR}}' | Format-Table Name,Length,LastWriteTime -AutoSize"

  status:
    desc: Show Docker container status
    cmds:
      - docker compose ps

  health:
    desc: Check if the application is responding
    cmds:
      - pwsh ./scripts/health-check.ps1

  # ============================================
  # Image Generation Tasks (Windows-compatible)
  # ============================================

  image:gen:
    desc: Generate image via ChatGPT (interactive Claude session)
    vars:
      PROMPT: '{{.CLI_ARGS}}'
      TIMESTAMP:
        sh: pwsh -NoProfile -Command "(Get-Date).ToString('yyyyMMdd_HHmmss')"
    interactive: true
    cmds:
      - pwsh -NoProfile -Command "New-Item -ItemType Directory -Path '.data/gpt-images' -Force -ErrorAction SilentlyContinue | Out-Null"
      - 'claude --chrome "Generate an image using ChatGPT. Navigate to chatgpt.com, enter prompt: {{.PROMPT}}, wait for generation, click Save, then copy from Downloads to .data/gpt-images/{{.TIMESTAMP}}_image.png"'

  image:gen:cmd:
    desc: Print claude command for image generation (copy and run manually)
    vars:
      PROMPT: '{{.CLI_ARGS}}'
      TIMESTAMP:
        sh: pwsh -NoProfile -Command "(Get-Date).ToString('yyyyMMdd_HHmmss')"
    cmds:
      - pwsh -NoProfile -Command "New-Item -ItemType Directory -Path '.data/gpt-images' -Force -ErrorAction SilentlyContinue | Out-Null"
      - 'pwsh -NoProfile -Command "Write-Host ''Run this command:''; Write-Host ''''; Write-Host ''claude --chrome ''''Generate an image using ChatGPT. Navigate to chatgpt.com, enter prompt: {{.PROMPT}}, wait for generation, click Save, then copy from Downloads to .data/gpt-images/{{.TIMESTAMP}}_image.png''''''''"'
